ROOT: '/your/data/root/CUB_200_2011'
DATA: 'CUB'
ARCH: 'vgg16'
RESUME: ''
DEBUG: 'debug'
LOG_DIR: 'log/'
NUM_THRESHOLD: 20
C_BASE: 64
WORKERS: 8
EPOCHS: 200
C_EPOCHS: 70
R_EPOCHS: 30
BATCH_SIZE: 16
LR: 0.001
C_LR: 0.001
R_LR: 0.0001
WEIGHT_DECAY: 0.0005
MOMENTUM: 0.9
PRINT_FREQ: 25
NUM_CLASSES: 200
SEED: 1
EXPERIMENT: ''
EVALUTATE: False
ATT_CHECKPOINT: 'debug/checkpoints/cub_coarse_best_model/last_epoch.pth'
CLS_CHECKPOINT: 'debug/checkpoints/evaluator/best_epoch.pth'
